package com.tfm.busonotec_backend.controller;

import com.tfm.busonotec_backend.service.BusinessRecordService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.Map;
import java.util.UUID;

@RestController
@Tag(
    name = "Business Records",
    description = "Create and read real business data stored in the physical tables generated for business entities."
)
public class BusinessRecordController {
  private final BusinessRecordService service;

  public BusinessRecordController(BusinessRecordService service) {
    this.service = service;
  }

  @Operation(
      summary = "List records for a business entity",
      description = "Reads rows from the physical table associated with the business entity."
  )
  @ApiResponses({
      @ApiResponse(
          responseCode = "200",
          description = "Records returned.",
          content = @Content(
              mediaType = "application/json",
              array = @ArraySchema(schema = @Schema(
                  type = "object",
                  additionalProperties = Schema.AdditionalPropertiesValue.TRUE,
                  description = "Dynamic record whose keys are the entity field names."
              )),
              examples = @ExampleObject(value = """
                  [
                    {
                      "id": "58f2a6a4-8e72-4d4f-bb13-ecf5f1f2c7c1",
                      "score": 95,
                      "active": true
                    }
                  ]
                  """)
          )
      ),
      @ApiResponse(responseCode = "400", description = "Invalid business entity UUID or missing physical table.", content = @Content),
      @ApiResponse(responseCode = "404", description = "Business entity not found.", content = @Content)
  })
  @GetMapping({"/api/business-entities/{businessEntityId}/records", "/api/entities/{businessEntityId}/records"})
  public ResponseEntity<List<Map<String, Object>>> listByBusinessEntity(
      @Parameter(
          description = "Business entity UUID.",
          example = "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          required = true
      )
      @PathVariable("businessEntityId") UUID businessEntityId
  ) {
    return ResponseEntity.ok(service.listByBusinessEntity(businessEntityId));
  }

  @Operation(
      summary = "Create a record for a business entity",
      description = "Inserts a row into the physical table associated with the business entity. The request body is dynamic: keys must match fields previously registered for the entity. The record id is generated by the backend."
  )
  @ApiResponses({
      @ApiResponse(
          responseCode = "200",
          description = "Record created.",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(
                  type = "object",
                  additionalProperties = Schema.AdditionalPropertiesValue.TRUE,
                  description = "Created dynamic record including the generated id."
              ),
              examples = @ExampleObject(value = """
                  {
                    "id": "58f2a6a4-8e72-4d4f-bb13-ecf5f1f2c7c1",
                    "score": 95,
                    "active": true
                  }
                  """)
          )
      ),
      @ApiResponse(responseCode = "400", description = "Invalid field, unknown field, duplicated field, reserved id, or missing physical table.", content = @Content),
      @ApiResponse(responseCode = "404", description = "Business entity not found.", content = @Content)
  })
  @PostMapping({"/api/business-entities/{businessEntityId}/records", "/api/entities/{businessEntityId}/records"})
  public ResponseEntity<Map<String, Object>> create(
      @Parameter(
          description = "Business entity UUID.",
          example = "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          required = true
      )
      @PathVariable("businessEntityId") UUID businessEntityId,
      @io.swagger.v3.oas.annotations.parameters.RequestBody(
          required = true,
          description = "Dynamic record values. Keys must match fields registered for the business entity. Do not send id.",
          content = @Content(
              mediaType = "application/json",
              schema = @Schema(
                  type = "object",
                  additionalProperties = Schema.AdditionalPropertiesValue.TRUE,
                  description = "Dynamic JSON object with business field names as keys."
              ),
              examples = @ExampleObject(value = """
                  {
                    "score": 95,
                    "active": true
                  }
                  """)
          )
      )
      @RequestBody Map<String, Object> record
  ) {
    return ResponseEntity.ok(service.create(businessEntityId, record));
  }
}
