spring:
  application:
    name: busonotec-backend
  datasource:
    url: "jdbc:postgresql://localhost:5432/busonotec-db"
    username: "busonotec-user"
    password: "busonotec-pass"
    driver-class-name: org.postgresql.Driver
